# FROM gcc:4.9 as builder
# RUN apt-get update && apt-get install -y libboost-all-dev libquantlib0-dev swig
# ADD . /go/src/github.com/gooption-io/gooption/goql
# WORKDIR /go/src/github.com/gooption-io/gooption/goql
# RUN ./build.sh

FROM grpc/cxx
EXPOSE 8080
EXPOSE 50051
COPY goql .
CMD ["./goql"]
