FROM golang:1.10 as builder
RUN apt-get update && apt-get install -y libboost-all-dev libquantlib0-dev swig
ADD . /go/src/github.com/gooption-io/gooption/goql
WORKDIR /go/src/github.com/gooption-io/gooption/goql
RUN CGO_ENABLED=1 go get -v
RUN CGO_ENABLED=1 GOOS=linux go build --ldflags '-w -extldflags "-static"'

FROM scratch
EXPOSE 8080
EXPOSE 8081
EXPOSE 50051
COPY --from=builder /go/src/github.com/gooption-io/gooption/goql/goql /
COPY goql.yml /etc/goql/goql.yml
CMD ["/goql"]
