# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang:1.7
RUN apt-get update
RUN apt-get install -y libquantlib0-dev

COPY goquantlib.yml /etc/goquantlib/goquantlib.yml

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/goquantlib

# Build the outyet command inside the container.
# (You may fetch or manage dependencies here,
# either manually or with a tool like "godep".)
RUN go install --ldflags '-extldflags "-static"' github.com/gooption/goquantlib/...

# Run the outyet command by default when the container starts.
ENTRYPOINT goquantlib

# Document that the service listens on port 8080.
EXPOSE 50051
EXPOSE 8081
EXPOSE 8080
