workspace:
  base: /go
  path: src/github.com/gooption-io/gooption

pipeline:
  build-gobs:
    image: golang:1.10
    commands:
      - cd gobs
      - go build
      - go test

  docker-gobs:
    image: plugins/docker:latest
    repo: gooption/gobs
    tags:
      - v0
      - dev
    dockerfile: ./gobs/dockerfile
    context: ./gobs
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]