workspace:
  base: /go
  path: src/github.com/gooption-io/gooption

pipeline:
  build-gobs:
    image: golang:1.10
    commands:
      - cd gobs
      - go get -v
      - go build
      - go test

  docker-gobs:
    image: plugins/docker:latest
    repo: gooption/gobs
    tags:
      - v0
    dockerfile: ./gobs/dockerfile
    context: ./gobs
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  
  build-goquantlib:
    image: golang:1.10
    commands:
      - cd goquantlib
      - go get
      - go build
      - go test
      
  docker-goquantlib:
    image: plugins/docker:1.12
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: gooption/goquantlib
    tags:
      - v0
    dockerfile: ./dockerfile
    context: ./goquantlib
