workspace:
  base: /go
  path: src/github.com/gooption-io/gooption

pipeline:
  build-gobs:
    image: golang:1.10
    commands:
      - cd gobs
      - go get -v
      - go build
      - go test

  docker-gobs:
    image: plugins/docker:latest
    repo: gooption/gobs
    tags:
      - v0
    dockerfile: ./gobs/dockerfile
    context: ./gobs
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
 
    
  build-goquantlib:
    image: golang:1.10
    commands:
      - apt-get update && apt-get install -y libboost-all-dev libquantlib0-dev swig
      - cd goquantlib
      - go get -v
      - go build
      - go test
      
  docker-goquantlib:
    image: plugins/docker:latest
    repo: gooption/goquantlib
    tags:
      - v0
    dockerfile: ./goquantlib/dockerfile
    context: ./goquantlib
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
