workspace:
  base: /go
  path: src/github.com/gooption-io/gooption

pipeline:

  build-gobs:
    image: golang:1.10
    commands:
      - cd gobs
      - go get -v
      - go build
      - go test

  docker-gobs:
    image: plugins/docker:latest
    repo: gooption/gobs
    tags:
      - v0
      - dev
    dockerfile: ./gobs/dockerfile
    context: ./gobs
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  
  build-goquantlib:
    image: golang:1.10
    commands:
      - apt-get update && apt-get install -y libboost-all-dev libquantlib0-dev swig
      - cd goquantlib
      - go get -v
      - go build
      - go test
      
  docker-goquantlib:
    image: plugins/docker:latest
    repo: gooption/goquantlib
    tags:
      - v0
      - dev
    dockerfile: ./goquantlib/dockerfile
    context: ./goquantlib
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    
  scp-copy:
    image: appleboy/drone-scp:latest
    pull: true
    host: gooption.io
    username: root
    volumes:
      - /root/drone_rsa:/root/ssh/drone_rsa
    key_path: /root/ssh/drone_rsa
    target: /
    source: /go/src/github.com/gooption-io/gooption
  
  ssh-docker-compose-up:
    image: appleboy/drone-ssh:latest
    pull: true
    host: gooption.io
    username: root
    volumes:
      - /root/drone_rsa:/root/ssh/drone_rsa
    key_path: /root/ssh/drone_rsa
    script:
      - /usr/local/bin/docker-compose -f /go/src/github.com/gooption-io/gooption/docker-compose-dev.yml up -d

