version: '3.6'
services:
  gobs:
    image: gooption/gobs:dev
    command: /gobs -config=/etc/gobs/gobs.yml
    volumes:
      - "./gobs/gobs-dev.yml:/etc/gobs/gobs.yml"
    ports:
     - 1001:1001
     - 1002:1002
     - 1003:1003

  goql:
    image: gooption/goql:dev
    command: /goql -config=/etc/goql/goql.yml
    volumes:
      - "./goql/goql-dev.yml:/etc/goql/goql.yml"
    ports:
     - 1011:1011
     - 1012:1012
     - 1013:1013

  prometheus:
    image: prom/prometheus:v2.3.0
    volumes:
      - "./prometheus-dev.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  exporter:
    image: prom/node-exporter:v0.16.0
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana:5.1.3
    volumes:
      - grafana-data:/var/lib/grafana
    user: 'root'
    ports:
      - 3000:3000
  zero:
    image: dgraph/dgraph:v1.0.5
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  server:
    image: dgraph/dgraph:v1.0.5
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph server --my=server:7080 --lru_mb=2048 --zero=zero:5080

  ratel:
    image: dgraph/dgraph:v1.0.5
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes:
  prometheus-data:
  grafana-data:
  dgraph-data:
