version: '3.6'
services:
  gobs:
    image: gooption/gobs:dev
    command: /gobs -config=/etc/gobs/gobs.yml
    volumes:
      - "./gobs/gobs.yml:/etc/gobs/gobs.yml"
    ports:
<<<<<<< HEAD
     - 18080:8080
     - 18081:8081
     - 18082:50051

=======
     - 8080:8080
     - 8081:8081
     - 50051:50051
    networks:
      - back-end
  
>>>>>>> 94b72e67ab82cf9bde7a6a121cde4dfb0c3d25d8
  prometheus:
    image: prom/prometheus:v2.3.0
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
      
  exporter:
    image: prom/node-exporter:v0.16.0
    ports:
      - 9100:9100
      
  grafana:
    image: grafana/grafana:5.1.3
    volumes:
      - grafana-data:/var/lib/grafana
    user: 'root'
    ports:
      - 3000:3000
<<<<<<< HEAD
=======
    networks: 
      - front-end
      - back-end

>>>>>>> 94b72e67ab82cf9bde7a6a121cde4dfb0c3d25d8
  zero:
    image: dgraph/dgraph:v1.0.5
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  
  server:
    image: dgraph/dgraph:v1.0.5
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8082:8082
      - 9082:9082
    restart: on-failure
    command: dgraph server --port_offset=2 --my=server:7080 --lru_mb=2048 --zero=zero:5080

  ratel:
    image: dgraph/dgraph:v1.0.5
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8009:8000
    command: dgraph-ratel

volumes:
  prometheus-data:
  grafana-data:
  dgraph-data:
