version: '3.6'
services:
  gobs:
    image: gooption/gobs:manual
    ports:
     - 8083:8080
     - 50051:50051
    networks:
      back-end:

  gateway:
    image: gooption/gateway:manual
    command: gooption gateway --grpc-address=gobs:50051
    ports:
    - 8081:8081
    networks:
      back-end:

networks:
  back-end:
