// Code generated by protoc-gen-go. DO NOT EDIT.
// source: european_pricer.proto

package api_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	api "github.com/gooption-io/gooption/contract/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ComputationRequest struct {
	Pricingdate          float64         `protobuf:"fixed64,2,opt,name=pricingdate,proto3" json:"pricingdate,omitempty"`
	Contract             *api.European   `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Spot                 *api.StockQuote `protobuf:"bytes,4,opt,name=spot,proto3" json:"spot,omitempty"`
	Vol                  float64         `protobuf:"fixed64,5,opt,name=vol,proto3" json:"vol,omitempty"`
	Rate                 float64         `protobuf:"fixed64,6,opt,name=rate,proto3" json:"rate,omitempty"`
	Greek                []string        `protobuf:"bytes,7,rep,name=greek,proto3" json:"greek,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ComputationRequest) Reset()         { *m = ComputationRequest{} }
func (m *ComputationRequest) String() string { return proto.CompactTextString(m) }
func (*ComputationRequest) ProtoMessage()    {}
func (*ComputationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5af2df7a4d0db1, []int{0}
}

func (m *ComputationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputationRequest.Unmarshal(m, b)
}
func (m *ComputationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputationRequest.Marshal(b, m, deterministic)
}
func (m *ComputationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputationRequest.Merge(m, src)
}
func (m *ComputationRequest) XXX_Size() int {
	return xxx_messageInfo_ComputationRequest.Size(m)
}
func (m *ComputationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputationRequest proto.InternalMessageInfo

func (m *ComputationRequest) GetPricingdate() float64 {
	if m != nil {
		return m.Pricingdate
	}
	return 0
}

func (m *ComputationRequest) GetContract() *api.European {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *ComputationRequest) GetSpot() *api.StockQuote {
	if m != nil {
		return m.Spot
	}
	return nil
}

func (m *ComputationRequest) GetVol() float64 {
	if m != nil {
		return m.Vol
	}
	return 0
}

func (m *ComputationRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *ComputationRequest) GetGreek() []string {
	if m != nil {
		return m.Greek
	}
	return nil
}

type ComputationResponse struct {
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Greeks               []*Greek `protobuf:"bytes,3,rep,name=greeks,proto3" json:"greeks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputationResponse) Reset()         { *m = ComputationResponse{} }
func (m *ComputationResponse) String() string { return proto.CompactTextString(m) }
func (*ComputationResponse) ProtoMessage()    {}
func (*ComputationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5af2df7a4d0db1, []int{1}
}

func (m *ComputationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputationResponse.Unmarshal(m, b)
}
func (m *ComputationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputationResponse.Marshal(b, m, deterministic)
}
func (m *ComputationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputationResponse.Merge(m, src)
}
func (m *ComputationResponse) XXX_Size() int {
	return xxx_messageInfo_ComputationResponse.Size(m)
}
func (m *ComputationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputationResponse proto.InternalMessageInfo

func (m *ComputationResponse) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ComputationResponse) GetGreeks() []*Greek {
	if m != nil {
		return m.Greeks
	}
	return nil
}

type Greek struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greek) Reset()         { *m = Greek{} }
func (m *Greek) String() string { return proto.CompactTextString(m) }
func (*Greek) ProtoMessage()    {}
func (*Greek) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5af2df7a4d0db1, []int{2}
}

func (m *Greek) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greek.Unmarshal(m, b)
}
func (m *Greek) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greek.Marshal(b, m, deterministic)
}
func (m *Greek) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greek.Merge(m, src)
}
func (m *Greek) XXX_Size() int {
	return xxx_messageInfo_Greek.Size(m)
}
func (m *Greek) XXX_DiscardUnknown() {
	xxx_messageInfo_Greek.DiscardUnknown(m)
}

var xxx_messageInfo_Greek proto.InternalMessageInfo

func (m *Greek) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Greek) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Greek) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ComputationRequest)(nil), "gooption.gobs.ComputationRequest")
	proto.RegisterType((*ComputationResponse)(nil), "gooption.gobs.ComputationResponse")
	proto.RegisterType((*Greek)(nil), "gooption.gobs.Greek")
}

func init() { proto.RegisterFile("european_pricer.proto", fileDescriptor_dd5af2df7a4d0db1) }

var fileDescriptor_dd5af2df7a4d0db1 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0x55, 0x9a, 0x7e, 0xba, 0xea, 0x6a, 0xd7, 0x6d, 0xa5, 0xa8, 0xbb, 0x2b, 0x65, 0x73, 0x8a,
	0x56, 0xbb, 0x89, 0x5a, 0x0e, 0x48, 0x70, 0x03, 0x21, 0xc4, 0x0d, 0xd2, 0x13, 0x5c, 0x2a, 0x27,
	0x58, 0x21, 0x6a, 0x9a, 0x71, 0x6d, 0xa7, 0x47, 0x0e, 0xfc, 0x05, 0x7e, 0x1a, 0x77, 0x4e, 0xfc,
	0x10, 0x64, 0x3b, 0x89, 0x28, 0x20, 0x6e, 0xf3, 0xde, 0xbc, 0x99, 0x79, 0x33, 0x36, 0x9a, 0xd2,
	0x92, 0x03, 0xa3, 0xa4, 0x58, 0x31, 0x9e, 0x25, 0x94, 0x07, 0x8c, 0x83, 0x04, 0x3c, 0x4a, 0x01,
	0x98, 0xcc, 0xa0, 0x08, 0x52, 0x88, 0xc5, 0xec, 0x57, 0x0a, 0x90, 0xe6, 0x34, 0x24, 0x2c, 0x0b,
	0x49, 0x51, 0x80, 0x24, 0x2a, 0x27, 0x8c, 0x78, 0xf6, 0xad, 0xee, 0x51, 0xe1, 0x1f, 0x42, 0x42,
	0xb2, 0x5e, 0x6d, 0x4b, 0x90, 0xd4, 0x50, 0xde, 0xb3, 0x85, 0xf0, 0x29, 0x6c, 0x58, 0x69, 0x2a,
	0x23, 0xba, 0x2d, 0xa9, 0x90, 0xd8, 0x45, 0x43, 0x35, 0x36, 0x2b, 0xd2, 0x5b, 0x22, 0xa9, 0xd3,
	0x72, 0x2d, 0xdf, 0x8a, 0xde, 0x52, 0xf8, 0x10, 0xf5, 0x13, 0x28, 0x24, 0x27, 0x89, 0x74, 0x6c,
	0xd7, 0xf2, 0x87, 0x8b, 0x9f, 0x41, 0xe3, 0xad, 0xce, 0x04, 0x67, 0x95, 0x81, 0xa8, 0x11, 0xe3,
	0x39, 0x6a, 0x0b, 0x06, 0xd2, 0x69, 0xeb, 0xa2, 0xdf, 0x9f, 0x14, 0x2d, 0x95, 0xcb, 0x2b, 0x65,
	0x32, 0xd2, 0x52, 0xfc, 0x1d, 0xd9, 0x3b, 0xc8, 0x9d, 0x8e, 0x76, 0xa1, 0x42, 0x8c, 0x51, 0x9b,
	0x2b, 0x63, 0x5d, 0x4d, 0xe9, 0x18, 0x4f, 0x50, 0x27, 0xe5, 0x94, 0xae, 0x9d, 0x9e, 0x6b, 0xfb,
	0x83, 0xc8, 0x00, 0xef, 0x1a, 0x8d, 0xf7, 0xf6, 0x13, 0x0c, 0x0a, 0xa1, 0xc5, 0xfa, 0xae, 0xd5,
	0x6a, 0x06, 0xe0, 0x7f, 0xa8, 0xab, 0xab, 0x84, 0x63, 0xbb, 0xb6, 0x3f, 0x5c, 0x4c, 0x82, 0xbd,
	0x73, 0x07, 0xe7, 0x2a, 0x19, 0x55, 0x1a, 0xef, 0x02, 0x75, 0x34, 0xa1, 0x9a, 0xe5, 0x24, 0xa6,
	0xb9, 0x63, 0xb9, 0x96, 0x9a, 0xac, 0x81, 0x62, 0x77, 0x24, 0x2f, 0x9b, 0x11, 0x1a, 0x28, 0x96,
	0x72, 0x0e, 0x5c, 0x1f, 0x6d, 0x10, 0x19, 0xb0, 0xb8, 0x47, 0xd3, 0xfa, 0x54, 0x97, 0xfa, 0xb9,
	0x97, 0x94, 0xef, 0x94, 0x23, 0x8a, 0x7a, 0xc6, 0x3e, 0xc5, 0x7f, 0xde, 0x99, 0xf9, 0xf8, 0x6c,
	0x33, 0xef, 0x2b, 0x89, 0xd9, 0xdc, 0x1b, 0x3f, 0x3c, 0xbd, 0x3c, 0xb6, 0x46, 0x5e, 0x3f, 0x4c,
	0x4c, 0xe3, 0x23, 0xeb, 0xef, 0xc9, 0xfc, 0x26, 0x4c, 0x33, 0x79, 0x57, 0xc6, 0x41, 0x02, 0x9b,
	0xb0, 0x6e, 0xf2, 0x3f, 0x83, 0x26, 0x0e, 0x55, 0x43, 0xf5, 0xcf, 0x8e, 0x09, 0xcb, 0x56, 0x2c,
	0x8e, 0xbb, 0xfa, 0x03, 0x1d, 0xbc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x2c, 0x0a, 0x5d, 0xa9,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EuropeanPricerServiceClient is the client API for EuropeanPricerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EuropeanPricerServiceClient interface {
	Compute(ctx context.Context, in *ComputationRequest, opts ...grpc.CallOption) (*ComputationResponse, error)
}

type europeanPricerServiceClient struct {
	cc *grpc.ClientConn
}

func NewEuropeanPricerServiceClient(cc *grpc.ClientConn) EuropeanPricerServiceClient {
	return &europeanPricerServiceClient{cc}
}

func (c *europeanPricerServiceClient) Compute(ctx context.Context, in *ComputationRequest, opts ...grpc.CallOption) (*ComputationResponse, error) {
	out := new(ComputationResponse)
	err := c.cc.Invoke(ctx, "/gooption.gobs.EuropeanPricerService/Compute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EuropeanPricerServiceServer is the server API for EuropeanPricerService service.
type EuropeanPricerServiceServer interface {
	Compute(context.Context, *ComputationRequest) (*ComputationResponse, error)
}

// UnimplementedEuropeanPricerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEuropeanPricerServiceServer struct {
}

func (*UnimplementedEuropeanPricerServiceServer) Compute(ctx context.Context, req *ComputationRequest) (*ComputationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compute not implemented")
}

func RegisterEuropeanPricerServiceServer(s *grpc.Server, srv EuropeanPricerServiceServer) {
	s.RegisterService(&_EuropeanPricerService_serviceDesc, srv)
}

func _EuropeanPricerService_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EuropeanPricerServiceServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gooption.gobs.EuropeanPricerService/Compute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EuropeanPricerServiceServer).Compute(ctx, req.(*ComputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EuropeanPricerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gooption.gobs.EuropeanPricerService",
	HandlerType: (*EuropeanPricerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compute",
			Handler:    _EuropeanPricerService_Compute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "european_pricer.proto",
}
