FROM gooption/builder:latest as builder
ADD . /go/src/github.com/gooption-io/gooption/gobs
WORKDIR /go/src/github.com/gooption-io/gooption/gobs
RUN CGO_ENABLED=0 GOOS=linux go build

FROM scratch
EXPOSE 8080
EXPOSE 50051
COPY --from=builder /go/src/github.com/gooption-io/gooption/gobs/gobs /
CMD ["/gobs"]