---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gobs-configmap
data:
  gobs.yml: |-
    # my global config
    tcp :50051
    http :8081
    promhttp :8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobs
  labels:
    app: gobs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gobs
  template:
    metadata:
      labels:
        app: gobs
    spec:
      containers:
      - name: gobs
        image: gooption/gobs:0.1
        command:
        - "/gobs"
        args:
        - " -config=/etc/gobs/gobs.yml"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 50051
        volumeMounts:
        - name: gobs-config
          mountPath: /etc/gobs
      volumes:
        - name: gobs-config
          configMap:
            name: gobs-configmap
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gobs
  labels:
    app: gobs
spec:
  selector:
    app: gobs
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    name: promhttp
  - port: 8081
    targetPort: 8081
    name: http
  - port: 50051
    targetPort: 50051
    name: tcp
---
