// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketdata.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Index struct {
	Timestamp float32 `protobuf:"fixed32,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ticker    string  `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Value     float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Index) Reset()                    { *m = Index{} }
func (m *Index) String() string            { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()               {}
func (*Index) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{0} }

func (m *Index) GetTimestamp() float32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Index) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Index) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Spot struct {
	Index *Index `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
}

func (m *Spot) Reset()                    { *m = Spot{} }
func (m *Spot) String() string            { return proto.CompactTextString(m) }
func (*Spot) ProtoMessage()               {}
func (*Spot) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{1} }

func (m *Spot) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

type RiskFreeRate struct {
	Index *Index `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
}

func (m *RiskFreeRate) Reset()                    { *m = RiskFreeRate{} }
func (m *RiskFreeRate) String() string            { return proto.CompactTextString(m) }
func (*RiskFreeRate) ProtoMessage()               {}
func (*RiskFreeRate) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{2} }

func (m *RiskFreeRate) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

type FlatVol struct {
	Index *Index `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
}

func (m *FlatVol) Reset()                    { *m = FlatVol{} }
func (m *FlatVol) String() string            { return proto.CompactTextString(m) }
func (*FlatVol) ProtoMessage()               {}
func (*FlatVol) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{3} }

func (m *FlatVol) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

type OptionQuote struct {
	Timestamp    float32    `protobuf:"fixed32,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Strike       float64    `protobuf:"fixed64,8,opt,name=strike,proto3" json:"strike,omitempty"`
	Bid          float64    `protobuf:"fixed64,9,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask          float64    `protobuf:"fixed64,10,opt,name=ask,proto3" json:"ask,omitempty"`
	Volume       float32    `protobuf:"fixed32,11,opt,name=volume,proto3" json:"volume,omitempty"`
	Openinterest float32    `protobuf:"fixed32,12,opt,name=openinterest,proto3" json:"openinterest,omitempty"`
	Putcall      OptionType `protobuf:"varint,13,opt,name=putcall,proto3,enum=pb.OptionType" json:"putcall,omitempty"`
}

func (m *OptionQuote) Reset()                    { *m = OptionQuote{} }
func (m *OptionQuote) String() string            { return proto.CompactTextString(m) }
func (*OptionQuote) ProtoMessage()               {}
func (*OptionQuote) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{4} }

func (m *OptionQuote) GetTimestamp() float32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OptionQuote) GetStrike() float64 {
	if m != nil {
		return m.Strike
	}
	return 0
}

func (m *OptionQuote) GetBid() float64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *OptionQuote) GetAsk() float64 {
	if m != nil {
		return m.Ask
	}
	return 0
}

func (m *OptionQuote) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *OptionQuote) GetOpeninterest() float32 {
	if m != nil {
		return m.Openinterest
	}
	return 0
}

func (m *OptionQuote) GetPutcall() OptionType {
	if m != nil {
		return m.Putcall
	}
	return OptionType_PUT
}

type OptionQuoteSlice struct {
	Timestamp float32        `protobuf:"fixed32,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Expiry    float32        `protobuf:"fixed32,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Puts      []*OptionQuote `protobuf:"bytes,3,rep,name=puts" json:"puts,omitempty"`
	Calls     []*OptionQuote `protobuf:"bytes,4,rep,name=calls" json:"calls,omitempty"`
}

func (m *OptionQuoteSlice) Reset()                    { *m = OptionQuoteSlice{} }
func (m *OptionQuoteSlice) String() string            { return proto.CompactTextString(m) }
func (*OptionQuoteSlice) ProtoMessage()               {}
func (*OptionQuoteSlice) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{5} }

func (m *OptionQuoteSlice) GetTimestamp() float32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OptionQuoteSlice) GetExpiry() float32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *OptionQuoteSlice) GetPuts() []*OptionQuote {
	if m != nil {
		return m.Puts
	}
	return nil
}

func (m *OptionQuoteSlice) GetCalls() []*OptionQuote {
	if m != nil {
		return m.Calls
	}
	return nil
}

type OptionMarket struct {
	Timestamp float32       `protobuf:"fixed32,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Spot      *Spot         `protobuf:"bytes,2,opt,name=spot" json:"spot,omitempty"`
	Vol       *FlatVol      `protobuf:"bytes,3,opt,name=vol" json:"vol,omitempty"`
	Rate      *RiskFreeRate `protobuf:"bytes,4,opt,name=rate" json:"rate,omitempty"`
}

func (m *OptionMarket) Reset()                    { *m = OptionMarket{} }
func (m *OptionMarket) String() string            { return proto.CompactTextString(m) }
func (*OptionMarket) ProtoMessage()               {}
func (*OptionMarket) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{6} }

func (m *OptionMarket) GetTimestamp() float32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OptionMarket) GetSpot() *Spot {
	if m != nil {
		return m.Spot
	}
	return nil
}

func (m *OptionMarket) GetVol() *FlatVol {
	if m != nil {
		return m.Vol
	}
	return nil
}

func (m *OptionMarket) GetRate() *RiskFreeRate {
	if m != nil {
		return m.Rate
	}
	return nil
}

type ImpliedVolSlice struct {
	Timestamp         float32        `protobuf:"fixed32,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Iserror           bool           `protobuf:"varint,2,opt,name=iserror,proto3" json:"iserror,omitempty"`
	Expiry            float32        `protobuf:"fixed32,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Errors            []string       `protobuf:"bytes,4,rep,name=errors" json:"errors,omitempty"`
	Strikes           []float64      `protobuf:"fixed64,5,rep,packed,name=strikes" json:"strikes,omitempty"`
	Vols              []float64      `protobuf:"fixed64,6,rep,packed,name=vols" json:"vols,omitempty"`
	Nbsolveriteration []int64        `protobuf:"varint,7,rep,packed,name=nbsolveriteration" json:"nbsolveriteration,omitempty"`
	Quotes            []*OptionQuote `protobuf:"bytes,8,rep,name=quotes" json:"quotes,omitempty"`
}

func (m *ImpliedVolSlice) Reset()                    { *m = ImpliedVolSlice{} }
func (m *ImpliedVolSlice) String() string            { return proto.CompactTextString(m) }
func (*ImpliedVolSlice) ProtoMessage()               {}
func (*ImpliedVolSlice) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{7} }

func (m *ImpliedVolSlice) GetTimestamp() float32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ImpliedVolSlice) GetIserror() bool {
	if m != nil {
		return m.Iserror
	}
	return false
}

func (m *ImpliedVolSlice) GetExpiry() float32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *ImpliedVolSlice) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ImpliedVolSlice) GetStrikes() []float64 {
	if m != nil {
		return m.Strikes
	}
	return nil
}

func (m *ImpliedVolSlice) GetVols() []float64 {
	if m != nil {
		return m.Vols
	}
	return nil
}

func (m *ImpliedVolSlice) GetNbsolveriteration() []int64 {
	if m != nil {
		return m.Nbsolveriteration
	}
	return nil
}

func (m *ImpliedVolSlice) GetQuotes() []*OptionQuote {
	if m != nil {
		return m.Quotes
	}
	return nil
}

type ImpliedVolSurface struct {
	Timestamp  float32            `protobuf:"fixed32,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Volsurface []*ImpliedVolSlice `protobuf:"bytes,2,rep,name=volsurface" json:"volsurface,omitempty"`
}

func (m *ImpliedVolSurface) Reset()                    { *m = ImpliedVolSurface{} }
func (m *ImpliedVolSurface) String() string            { return proto.CompactTextString(m) }
func (*ImpliedVolSurface) ProtoMessage()               {}
func (*ImpliedVolSurface) Descriptor() ([]byte, []int) { return fileDescriptorMarketdata, []int{8} }

func (m *ImpliedVolSurface) GetTimestamp() float32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ImpliedVolSurface) GetVolsurface() []*ImpliedVolSlice {
	if m != nil {
		return m.Volsurface
	}
	return nil
}

func init() {
	proto.RegisterType((*Index)(nil), "pb.Index")
	proto.RegisterType((*Spot)(nil), "pb.Spot")
	proto.RegisterType((*RiskFreeRate)(nil), "pb.RiskFreeRate")
	proto.RegisterType((*FlatVol)(nil), "pb.FlatVol")
	proto.RegisterType((*OptionQuote)(nil), "pb.OptionQuote")
	proto.RegisterType((*OptionQuoteSlice)(nil), "pb.OptionQuoteSlice")
	proto.RegisterType((*OptionMarket)(nil), "pb.OptionMarket")
	proto.RegisterType((*ImpliedVolSlice)(nil), "pb.ImpliedVolSlice")
	proto.RegisterType((*ImpliedVolSurface)(nil), "pb.ImpliedVolSurface")
}
func (m *Index) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Index) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Timestamp))))
	}
	if len(m.Ticker) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(len(m.Ticker)))
		i += copy(dAtA[i:], m.Ticker)
	}
	if m.Value != 0 {
		dAtA[i] = 0x19
		i++
		i = encodeFixed64Marketdata(dAtA, i, uint64(math.Float64bits(float64(m.Value))))
	}
	return i, nil
}

func (m *Spot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Spot) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Index != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(m.Index.Size()))
		n1, err := m.Index.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *RiskFreeRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RiskFreeRate) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Index != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(m.Index.Size()))
		n2, err := m.Index.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *FlatVol) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FlatVol) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Index != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(m.Index.Size()))
		n3, err := m.Index.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func (m *OptionQuote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionQuote) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Timestamp))))
	}
	if m.Strike != 0 {
		dAtA[i] = 0x41
		i++
		i = encodeFixed64Marketdata(dAtA, i, uint64(math.Float64bits(float64(m.Strike))))
	}
	if m.Bid != 0 {
		dAtA[i] = 0x49
		i++
		i = encodeFixed64Marketdata(dAtA, i, uint64(math.Float64bits(float64(m.Bid))))
	}
	if m.Ask != 0 {
		dAtA[i] = 0x51
		i++
		i = encodeFixed64Marketdata(dAtA, i, uint64(math.Float64bits(float64(m.Ask))))
	}
	if m.Volume != 0 {
		dAtA[i] = 0x5d
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Volume))))
	}
	if m.Openinterest != 0 {
		dAtA[i] = 0x65
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Openinterest))))
	}
	if m.Putcall != 0 {
		dAtA[i] = 0x68
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(m.Putcall))
	}
	return i, nil
}

func (m *OptionQuoteSlice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionQuoteSlice) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Timestamp))))
	}
	if m.Expiry != 0 {
		dAtA[i] = 0x15
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Expiry))))
	}
	if len(m.Puts) > 0 {
		for _, msg := range m.Puts {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintMarketdata(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Calls) > 0 {
		for _, msg := range m.Calls {
			dAtA[i] = 0x22
			i++
			i = encodeVarintMarketdata(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *OptionMarket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionMarket) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Timestamp))))
	}
	if m.Spot != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(m.Spot.Size()))
		n4, err := m.Spot.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.Vol != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(m.Vol.Size()))
		n5, err := m.Vol.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.Rate != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(m.Rate.Size()))
		n6, err := m.Rate.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}

func (m *ImpliedVolSlice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ImpliedVolSlice) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Timestamp))))
	}
	if m.Iserror {
		dAtA[i] = 0x10
		i++
		if m.Iserror {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Expiry != 0 {
		dAtA[i] = 0x1d
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Expiry))))
	}
	if len(m.Errors) > 0 {
		for _, s := range m.Errors {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Strikes) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(len(m.Strikes)*8))
		for _, num := range m.Strikes {
			f7 := math.Float64bits(float64(num))
			dAtA[i] = uint8(f7)
			i++
			dAtA[i] = uint8(f7 >> 8)
			i++
			dAtA[i] = uint8(f7 >> 16)
			i++
			dAtA[i] = uint8(f7 >> 24)
			i++
			dAtA[i] = uint8(f7 >> 32)
			i++
			dAtA[i] = uint8(f7 >> 40)
			i++
			dAtA[i] = uint8(f7 >> 48)
			i++
			dAtA[i] = uint8(f7 >> 56)
			i++
		}
	}
	if len(m.Vols) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(len(m.Vols)*8))
		for _, num := range m.Vols {
			f8 := math.Float64bits(float64(num))
			dAtA[i] = uint8(f8)
			i++
			dAtA[i] = uint8(f8 >> 8)
			i++
			dAtA[i] = uint8(f8 >> 16)
			i++
			dAtA[i] = uint8(f8 >> 24)
			i++
			dAtA[i] = uint8(f8 >> 32)
			i++
			dAtA[i] = uint8(f8 >> 40)
			i++
			dAtA[i] = uint8(f8 >> 48)
			i++
			dAtA[i] = uint8(f8 >> 56)
			i++
		}
	}
	if len(m.Nbsolveriteration) > 0 {
		dAtA10 := make([]byte, len(m.Nbsolveriteration)*10)
		var j9 int
		for _, num1 := range m.Nbsolveriteration {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA10[j9] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j9++
			}
			dAtA10[j9] = uint8(num)
			j9++
		}
		dAtA[i] = 0x3a
		i++
		i = encodeVarintMarketdata(dAtA, i, uint64(j9))
		i += copy(dAtA[i:], dAtA10[:j9])
	}
	if len(m.Quotes) > 0 {
		for _, msg := range m.Quotes {
			dAtA[i] = 0x42
			i++
			i = encodeVarintMarketdata(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ImpliedVolSurface) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ImpliedVolSurface) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		dAtA[i] = 0xd
		i++
		i = encodeFixed32Marketdata(dAtA, i, uint32(math.Float32bits(float32(m.Timestamp))))
	}
	if len(m.Volsurface) > 0 {
		for _, msg := range m.Volsurface {
			dAtA[i] = 0x12
			i++
			i = encodeVarintMarketdata(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeFixed64Marketdata(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Marketdata(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMarketdata(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Index) Size() (n int) {
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 5
	}
	l = len(m.Ticker)
	if l > 0 {
		n += 1 + l + sovMarketdata(uint64(l))
	}
	if m.Value != 0 {
		n += 9
	}
	return n
}

func (m *Spot) Size() (n int) {
	var l int
	_ = l
	if m.Index != nil {
		l = m.Index.Size()
		n += 1 + l + sovMarketdata(uint64(l))
	}
	return n
}

func (m *RiskFreeRate) Size() (n int) {
	var l int
	_ = l
	if m.Index != nil {
		l = m.Index.Size()
		n += 1 + l + sovMarketdata(uint64(l))
	}
	return n
}

func (m *FlatVol) Size() (n int) {
	var l int
	_ = l
	if m.Index != nil {
		l = m.Index.Size()
		n += 1 + l + sovMarketdata(uint64(l))
	}
	return n
}

func (m *OptionQuote) Size() (n int) {
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 5
	}
	if m.Strike != 0 {
		n += 9
	}
	if m.Bid != 0 {
		n += 9
	}
	if m.Ask != 0 {
		n += 9
	}
	if m.Volume != 0 {
		n += 5
	}
	if m.Openinterest != 0 {
		n += 5
	}
	if m.Putcall != 0 {
		n += 1 + sovMarketdata(uint64(m.Putcall))
	}
	return n
}

func (m *OptionQuoteSlice) Size() (n int) {
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 5
	}
	if m.Expiry != 0 {
		n += 5
	}
	if len(m.Puts) > 0 {
		for _, e := range m.Puts {
			l = e.Size()
			n += 1 + l + sovMarketdata(uint64(l))
		}
	}
	if len(m.Calls) > 0 {
		for _, e := range m.Calls {
			l = e.Size()
			n += 1 + l + sovMarketdata(uint64(l))
		}
	}
	return n
}

func (m *OptionMarket) Size() (n int) {
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 5
	}
	if m.Spot != nil {
		l = m.Spot.Size()
		n += 1 + l + sovMarketdata(uint64(l))
	}
	if m.Vol != nil {
		l = m.Vol.Size()
		n += 1 + l + sovMarketdata(uint64(l))
	}
	if m.Rate != nil {
		l = m.Rate.Size()
		n += 1 + l + sovMarketdata(uint64(l))
	}
	return n
}

func (m *ImpliedVolSlice) Size() (n int) {
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 5
	}
	if m.Iserror {
		n += 2
	}
	if m.Expiry != 0 {
		n += 5
	}
	if len(m.Errors) > 0 {
		for _, s := range m.Errors {
			l = len(s)
			n += 1 + l + sovMarketdata(uint64(l))
		}
	}
	if len(m.Strikes) > 0 {
		n += 1 + sovMarketdata(uint64(len(m.Strikes)*8)) + len(m.Strikes)*8
	}
	if len(m.Vols) > 0 {
		n += 1 + sovMarketdata(uint64(len(m.Vols)*8)) + len(m.Vols)*8
	}
	if len(m.Nbsolveriteration) > 0 {
		l = 0
		for _, e := range m.Nbsolveriteration {
			l += sovMarketdata(uint64(e))
		}
		n += 1 + sovMarketdata(uint64(l)) + l
	}
	if len(m.Quotes) > 0 {
		for _, e := range m.Quotes {
			l = e.Size()
			n += 1 + l + sovMarketdata(uint64(l))
		}
	}
	return n
}

func (m *ImpliedVolSurface) Size() (n int) {
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 5
	}
	if len(m.Volsurface) > 0 {
		for _, e := range m.Volsurface {
			l = e.Size()
			n += 1 + l + sovMarketdata(uint64(l))
		}
	}
	return n
}

func sovMarketdata(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMarketdata(x uint64) (n int) {
	return sovMarketdata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Index) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Index: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Index: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Timestamp = float32(math.Float32frombits(v))
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ticker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Value = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Spot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Spot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Spot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Index == nil {
				m.Index = &Index{}
			}
			if err := m.Index.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RiskFreeRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RiskFreeRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RiskFreeRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Index == nil {
				m.Index = &Index{}
			}
			if err := m.Index.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FlatVol) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FlatVol: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FlatVol: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Index == nil {
				m.Index = &Index{}
			}
			if err := m.Index.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OptionQuote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionQuote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionQuote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Timestamp = float32(math.Float32frombits(v))
		case 8:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strike", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Strike = float64(math.Float64frombits(v))
		case 9:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bid", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Bid = float64(math.Float64frombits(v))
		case 10:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ask", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Ask = float64(math.Float64frombits(v))
		case 11:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Volume = float32(math.Float32frombits(v))
		case 12:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Openinterest", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Openinterest = float32(math.Float32frombits(v))
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Putcall", wireType)
			}
			m.Putcall = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Putcall |= (OptionType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OptionQuoteSlice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionQuoteSlice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionQuoteSlice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Timestamp = float32(math.Float32frombits(v))
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Expiry = float32(math.Float32frombits(v))
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Puts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Puts = append(m.Puts, &OptionQuote{})
			if err := m.Puts[len(m.Puts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Calls", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Calls = append(m.Calls, &OptionQuote{})
			if err := m.Calls[len(m.Calls)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OptionMarket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionMarket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionMarket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Timestamp = float32(math.Float32frombits(v))
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Spot == nil {
				m.Spot = &Spot{}
			}
			if err := m.Spot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vol", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vol == nil {
				m.Vol = &FlatVol{}
			}
			if err := m.Vol.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Rate == nil {
				m.Rate = &RiskFreeRate{}
			}
			if err := m.Rate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ImpliedVolSlice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ImpliedVolSlice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ImpliedVolSlice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Timestamp = float32(math.Float32frombits(v))
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Iserror", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Iserror = bool(v != 0)
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Expiry = float32(math.Float32frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Errors", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Errors = append(m.Errors, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				iNdEx += 8
				v = uint64(dAtA[iNdEx-8])
				v |= uint64(dAtA[iNdEx-7]) << 8
				v |= uint64(dAtA[iNdEx-6]) << 16
				v |= uint64(dAtA[iNdEx-5]) << 24
				v |= uint64(dAtA[iNdEx-4]) << 32
				v |= uint64(dAtA[iNdEx-3]) << 40
				v |= uint64(dAtA[iNdEx-2]) << 48
				v |= uint64(dAtA[iNdEx-1]) << 56
				v2 := float64(math.Float64frombits(v))
				m.Strikes = append(m.Strikes, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMarketdata
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMarketdata
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					iNdEx += 8
					v = uint64(dAtA[iNdEx-8])
					v |= uint64(dAtA[iNdEx-7]) << 8
					v |= uint64(dAtA[iNdEx-6]) << 16
					v |= uint64(dAtA[iNdEx-5]) << 24
					v |= uint64(dAtA[iNdEx-4]) << 32
					v |= uint64(dAtA[iNdEx-3]) << 40
					v |= uint64(dAtA[iNdEx-2]) << 48
					v |= uint64(dAtA[iNdEx-1]) << 56
					v2 := float64(math.Float64frombits(v))
					m.Strikes = append(m.Strikes, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Strikes", wireType)
			}
		case 6:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				iNdEx += 8
				v = uint64(dAtA[iNdEx-8])
				v |= uint64(dAtA[iNdEx-7]) << 8
				v |= uint64(dAtA[iNdEx-6]) << 16
				v |= uint64(dAtA[iNdEx-5]) << 24
				v |= uint64(dAtA[iNdEx-4]) << 32
				v |= uint64(dAtA[iNdEx-3]) << 40
				v |= uint64(dAtA[iNdEx-2]) << 48
				v |= uint64(dAtA[iNdEx-1]) << 56
				v2 := float64(math.Float64frombits(v))
				m.Vols = append(m.Vols, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMarketdata
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMarketdata
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					iNdEx += 8
					v = uint64(dAtA[iNdEx-8])
					v |= uint64(dAtA[iNdEx-7]) << 8
					v |= uint64(dAtA[iNdEx-6]) << 16
					v |= uint64(dAtA[iNdEx-5]) << 24
					v |= uint64(dAtA[iNdEx-4]) << 32
					v |= uint64(dAtA[iNdEx-3]) << 40
					v |= uint64(dAtA[iNdEx-2]) << 48
					v |= uint64(dAtA[iNdEx-1]) << 56
					v2 := float64(math.Float64frombits(v))
					m.Vols = append(m.Vols, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Vols", wireType)
			}
		case 7:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMarketdata
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Nbsolveriteration = append(m.Nbsolveriteration, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMarketdata
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMarketdata
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMarketdata
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Nbsolveriteration = append(m.Nbsolveriteration, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Nbsolveriteration", wireType)
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quotes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Quotes = append(m.Quotes, &OptionQuote{})
			if err := m.Quotes[len(m.Quotes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ImpliedVolSurface) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ImpliedVolSurface: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ImpliedVolSurface: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.Timestamp = float32(math.Float32frombits(v))
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volsurface", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarketdata
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Volsurface = append(m.Volsurface, &ImpliedVolSlice{})
			if err := m.Volsurface[len(m.Volsurface)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarketdata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMarketdata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMarketdata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMarketdata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarketdata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMarketdata
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMarketdata
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMarketdata(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMarketdata = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMarketdata   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("marketdata.proto", fileDescriptorMarketdata) }

var fileDescriptorMarketdata = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0x46, 0xb1, 0xf3, 0x77, 0xec, 0xb5, 0xa9, 0x36, 0x86, 0x18, 0x5d, 0x67, 0xbc, 0x8d, 0x9a,
	0x31, 0x32, 0x48, 0xdf, 0x60, 0x17, 0x85, 0x5e, 0x8c, 0x31, 0x65, 0xf4, 0x5e, 0x49, 0x54, 0x10,
	0x96, 0x2d, 0x4d, 0x92, 0x43, 0xfb, 0x14, 0xbb, 0xd9, 0x43, 0xed, 0x66, 0xb0, 0x47, 0x18, 0x79,
	0x90, 0x31, 0x24, 0x3b, 0x34, 0x61, 0x85, 0xf4, 0xce, 0xdf, 0xf7, 0x1d, 0x7d, 0x3a, 0xe7, 0xd3,
	0x49, 0x60, 0x52, 0x31, 0x53, 0x72, 0xb7, 0x62, 0x8e, 0x4d, 0xb5, 0x51, 0x4e, 0xe1, 0x9e, 0x5e,
	0xbc, 0x48, 0x97, 0xaa, 0xaa, 0x54, 0xdd, 0x32, 0xf9, 0x1c, 0xfa, 0x57, 0xf5, 0x8a, 0xdf, 0xe2,
	0x53, 0x18, 0x3b, 0x51, 0x71, 0xeb, 0x58, 0xa5, 0x09, 0xca, 0x50, 0xd1, 0xa3, 0xf7, 0x04, 0x7e,
	0x0e, 0x03, 0x27, 0x96, 0x25, 0x37, 0xa4, 0x97, 0xa1, 0x62, 0x4c, 0x3b, 0x84, 0x9f, 0x41, 0x7f,
	0xcd, 0x64, 0xc3, 0x49, 0x94, 0xa1, 0x02, 0xd1, 0x16, 0xe4, 0xe7, 0x10, 0xcf, 0xb5, 0x72, 0xf8,
	0x15, 0xf4, 0x85, 0x37, 0x0f, 0x7e, 0xc9, 0x6c, 0x3c, 0xd5, 0x8b, 0x69, 0xb8, 0x8d, 0xb6, 0x7c,
	0xfe, 0x01, 0x52, 0x2a, 0x6c, 0x79, 0x69, 0x38, 0xa7, 0xcc, 0xf1, 0xc3, 0x07, 0xde, 0xc1, 0xf0,
	0x52, 0x32, 0x77, 0xad, 0xe4, 0xe1, 0xda, 0x5f, 0x08, 0x92, 0xcf, 0xda, 0x09, 0x55, 0x7f, 0x69,
	0x94, 0xe3, 0x87, 0x27, 0xb4, 0xce, 0x88, 0x92, 0x93, 0x51, 0x18, 0xa5, 0x43, 0x78, 0x02, 0xd1,
	0x42, 0xac, 0xc8, 0x38, 0x90, 0xfe, 0xd3, 0x33, 0xcc, 0x96, 0x04, 0x5a, 0x86, 0xd9, 0xd2, 0x9f,
	0x5d, 0x2b, 0xd9, 0x54, 0x9c, 0x24, 0xc1, 0xb6, 0x43, 0x38, 0x87, 0x54, 0x69, 0x5e, 0x8b, 0xda,
	0x71, 0xc3, 0xad, 0x23, 0x69, 0x50, 0xf7, 0x38, 0x5c, 0xc0, 0x50, 0x37, 0x6e, 0xc9, 0xa4, 0x24,
	0x4f, 0x32, 0x54, 0x1c, 0xcd, 0x8e, 0xfc, 0x20, 0x6d, 0xdf, 0x5f, 0xef, 0x34, 0xa7, 0x5b, 0x39,
	0xff, 0x81, 0x60, 0xb2, 0x33, 0xcf, 0x5c, 0x8a, 0xe5, 0x23, 0x86, 0xe2, 0xb7, 0x5a, 0x98, 0xbb,
	0xf0, 0x6c, 0x3d, 0xda, 0x21, 0xfc, 0x1a, 0x62, 0xdd, 0x38, 0x4b, 0xa2, 0x2c, 0x2a, 0x92, 0xd9,
	0xf1, 0xfd, 0x8d, 0xc1, 0x99, 0x06, 0x11, 0xbf, 0x85, 0xbe, 0xbf, 0xd7, 0x92, 0xf8, 0xe1, 0xaa,
	0x56, 0xcd, 0xbf, 0x23, 0x48, 0x5b, 0xfa, 0x53, 0x58, 0xb7, 0x03, 0x2d, 0x9d, 0x42, 0x6c, 0xb5,
	0x72, 0xa1, 0xa1, 0x64, 0x36, 0xf2, 0xa6, 0x7e, 0x57, 0x68, 0x60, 0xf1, 0x4b, 0x88, 0xd6, 0x4a,
	0x86, 0x6d, 0x4a, 0x66, 0x89, 0x17, 0xbb, 0xe7, 0xa6, 0x9e, 0xc7, 0x6f, 0x20, 0x36, 0xcc, 0x71,
	0x12, 0x07, 0x7d, 0xe2, 0xf5, 0xdd, 0xfd, 0xa1, 0x41, 0xcd, 0xff, 0x22, 0x38, 0xbe, 0xaa, 0xb4,
	0x14, 0x7c, 0x75, 0xad, 0xe4, 0x63, 0x72, 0x22, 0x30, 0x14, 0x96, 0x1b, 0xa3, 0xda, 0xfd, 0x1e,
	0xd1, 0x2d, 0xdc, 0x49, 0x30, 0xda, 0x4b, 0xd0, 0xf3, 0xbe, 0xa0, 0x4d, 0x67, 0x4c, 0x3b, 0xe4,
	0x9d, 0xda, 0xc5, 0xb1, 0xa4, 0x9f, 0x45, 0x05, 0xa2, 0x5b, 0x88, 0x31, 0xc4, 0x6b, 0x25, 0x2d,
	0x19, 0x04, 0x3a, 0x7c, 0xe3, 0xf7, 0x70, 0x52, 0x2f, 0xac, 0x92, 0x6b, 0x6e, 0x84, 0xe3, 0x86,
	0xf9, 0x14, 0xc9, 0x30, 0x8b, 0x8a, 0x88, 0xfe, 0x2f, 0xe0, 0x73, 0x18, 0x7c, 0xf3, 0xc9, 0x5b,
	0x32, 0x7a, 0xf8, 0x45, 0x3a, 0x39, 0xbf, 0x81, 0x93, 0x9d, 0xf9, 0x1b, 0x73, 0xc3, 0x0e, 0x26,
	0x70, 0x01, 0xe0, 0x3b, 0x6a, 0x6b, 0x49, 0x2f, 0xf8, 0x3f, 0x0d, 0x3f, 0xa9, 0xfd, 0x20, 0xe9,
	0x4e, 0xd9, 0xc7, 0xf4, 0xe7, 0xe6, 0x0c, 0xfd, 0xde, 0x9c, 0xa1, 0x3f, 0x9b, 0x33, 0xb4, 0x18,
	0x84, 0x7f, 0x94, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x0d, 0x79, 0xf7, 0x77, 0x04,
	0x00, 0x00,
}
